[project]
name = "stackstrip"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.mock-ststx]
path = "contracts/mock-ststx.clar"
clarity_version = 3
epoch = "latest"

[contracts.pt-token]
path = "contracts/pt-token.clar"
clarity_version = 3
epoch = "latest"

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
clarity_version = 3
epoch = "latest"

[contracts.yt-token]
path = "contracts/yt-token.clar"
clarity_version = 3
epoch = "latest"

[contracts.amm]
path = "contracts/amm.clar"
clarity_version = 3
epoch = "latest"

[repl.costs_version]
version = 2

[contracts.yield-market]
path = "contracts/yield-market.clar"
clarity_version = 3
epoch = "latest"
